import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { mkdir, cp } from 'fs/promises';

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const prisma = new PrismaClient();

async function main() {
  const viewerDataDir = path.join(__dirname, '..', '..', 'viewer', 'public', 'data');
  const mobileAssetsDir = path.join(__dirname, '..', '..', 'Mobile', 'assets');
  const sourceDbPath = path.join(__dirname, '..', 'prisma', 'dev.db');
  
  if (!fs.existsSync(viewerDataDir)) {
    fs.mkdirSync(viewerDataDir, { recursive: true });
  }

  console.log('Fetching data from database...');
  
  const [persons, marriages] = await Promise.all([
    prisma.person.findMany({
      include: {
        father: { select: { id: true, firstName: true, lastName: true } },
        mother: { select: { id: true, firstName: true, lastName: true } },
      },
      orderBy: { firstName: 'asc' },
    }),
    prisma.marriage.findMany(),
  ]);

  console.log(`Found ${persons.length} persons and ${marriages.length} marriages`);

  // Copy images to viewer and mobile
  const imagesSrc = path.join(__dirname, '..', 'public', 'images', 'persons');
  const imagesViewerDest = path.join(__dirname, '..', '..', 'viewer', 'public', 'images', 'persons');
  const imagesMobileDest = path.join(__dirname, '..', '..', 'Mobile', 'assets', 'images', 'persons');

  if (fs.existsSync(imagesSrc)) {
    await mkdir(path.dirname(imagesViewerDest), { recursive: true });
    await cp(imagesSrc, imagesViewerDest, { recursive: true });
    console.log('Copied images to viewer');

    await mkdir(path.dirname(imagesMobileDest), { recursive: true });
    await cp(imagesSrc, imagesMobileDest, { recursive: true });
    console.log('Copied images to mobile');
  } else {
    console.log('No images to copy');
  }

  // Auto-detect profile images if null in DB
  const processedPersons = persons.map(p => {
    // If profileImage is null, check if profile.jpg exists
    if (!p.profileImage) {
      const relativePath = `images/persons/${p.id}/profile.jpg`;
      const fullPath = path.join(imagesMobileDest, p.id, 'profile.jpg');
      if (fs.existsSync(fullPath)) {
        p.profileImage = relativePath;
      }
    }
    return p;
  });

  // Generate Image Map for Mobile (to support require() for local assets)
  console.log('Generating image map for Mobile...');
  const imageMapEntries: string[] = [];
  
  function walkDir(dir: string, baseDir: string) {
    if (!fs.existsSync(dir)) return;
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        walkDir(fullPath, baseDir);
      } else if (file.endsWith('.jpg') || file.endsWith('.png') || file.endsWith('.jpeg')) {
        const relativePath = path.relative(baseDir, fullPath).replace(/\\/g, '/');
        const requirePath = `../assets/${relativePath}`;
        imageMapEntries.push(`  "${relativePath}": require("${requirePath}"),`);
      }
    }
  }

  walkDir(imagesMobileDest, path.join(__dirname, '..', '..', 'Mobile', 'assets'));

  const imageMapContent = `// This file is auto-generated by Web/scripts/export-json.ts
// Do not edit this file manually.
export const imageMap: Record<string, any> = {
${imageMapEntries.join('\n')}
};
`;
  const imageMapPath = path.join(__dirname, '..', '..', 'Mobile', 'src', 'imageMap.ts');
  if (!fs.existsSync(path.dirname(imageMapPath))) {
    fs.mkdirSync(path.dirname(imageMapPath), { recursive: true });
  }
  fs.writeFileSync(imageMapPath, imageMapContent);
  console.log('Generated Mobile/src/imageMap.ts');

  const data = { persons: processedPersons, marriages };
  
  const familyJsonPath = path.join(viewerDataDir, 'family.json');
  const familyJsonString = JSON.stringify(data, null, 2);
  fs.writeFileSync(familyJsonPath, familyJsonString);
  console.log(`Exported family.json to viewer`);

  if (!fs.existsSync(mobileAssetsDir)) {
    fs.mkdirSync(mobileAssetsDir, { recursive: true });
  }
  const mobileJsonPath = path.join(mobileAssetsDir, 'family.json');
  fs.writeFileSync(mobileJsonPath, familyJsonString);
  console.log(`Exported family.json to Mobile/assets`);

  console.log('Sync complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });